name: Build and Generate Translations

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        run: npm install

      - name: Cache translations
        uses: actions/cache@v3
        with:
          path: ./src/translations
          key: ${{ runner.os }}-build-${{ hashFiles('**/translations') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  generate-translations:
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: Run generate file translations
        run: npm run generate-json

  test-and-coverage:
    runs-on: ubuntu-latest
    needs: cache-and-install
    steps:
      - name: Run test
        run: npm run test

      - name: Checking coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 50

  build-and-upload:
    runs-on: ubuntu-latest
    needs: [cache-and-install, generate-translations, test-and-coverage]
    steps:
      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: Build
          path: dist/
