name: Deploy project

on:
  workflow_run:
    workflows: ["Build and Generate Translations"]  # Aquí el nombre exacto del workflow de construcción
    types:
      - completed

jobs:
  deploy-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build-artifact
          path: build

      - name: Download Translations Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: translations-artifact
          path: ./src/translations/

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_I18N }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_I18N }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
