name: CI with cache

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        
      - name: Install Dependencies
        run: npm install

      - name: Verify node modules
        run: ls -la node_modules

      - name: Save node modules
        if: success()
        run: tar -czf node_modules.tar.gz node_modules
        continue-on-error: true

  translation:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node modules
        if: success()
        run: tar -xzf ../install/node_modules.tar.gz
        continue-on-error: true
      
      - name: Verify node modules
        run: ls -la node_modules

      - name: Run generate file translations
        run: npm run generate-json

  build:
    runs-on: ubuntu-latest
    needs: 
      - install
      - translation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Restore node modules
        if: success()
        run: tar -xzf ../install/node_modules.tar.gz
        continue-on-error: true

      - name: Verify node modules
        run: ls -la node_modules

      - name: build
        run: npm run build
