# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy Test Automatization

on:
  workflow_dispatch:
  push:
    branches: ["main"] # Cambiar "main" por el nombre de la rama principal de tu repositorio (por ejemplo, "master" o "main")
  pull_request:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run generate file translations
        run: npm run generate-json

      - name: Build
        run: npm run build

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_I18N }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_I18N }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

